comit-network/comit-js-sdk

- src/cnd.ts
The ID is what is already returned by cnd, we just were ignoring it in the SDK.
> Make postSwap return the swap ID

- CHANGELOG.md
- package.json
To fix `0.5.0`:
This error appears when doing `yarn install` in create-comit-app example after upgrading to `comit-sdk:0.5.0`.
```
error /Users/froyer/src/create-comit-app/new_project/examples/erc20_btc/node_modules/comit-sdk: Command failed.
Exit code: 127
Command: mkdir -p ./gen && json2ts -i ./siren.schema.json -o ./gen/siren.d.ts && prettier --write ./gen/siren.d.ts
Arguments: 
```
> Fix json2ts

- .gitignore
- CHANGELOG.md
Files ignored by git are not included by `yarn publish`.
Moreover, we fixed the scripts so that we do expect to generate a dist folder as part of normal development.
> Pack dist/ folder

- CHANGELOG.md
- src/bitcoinWallet.ts
For difference check:
https://bitcoin.stackexchange.com/questions/77699/whats-the-difference-between-txid-and-hash-getrawtransaction-bitcoind
In order to request the TX from bitcoind REST API we need tx-id.
> Return tx-id instead of tx-hash to be able to request via REST-API

- README.md
The SDK can be used in a variety of ways, with examples/projects using create-comit-app being only one of them. In order to not confuse developers in what they can do with the SDK, we should not mention implementation details of how create-comit-app works here.
> Remove irrelevant documentation

- .gitignore
- CHANGELOG.md
- package.json
- src/cnd.ts
`cnd` has now been able to derive expiries for you [for a while](https://github.com/comit-network/comit-rs/pull/1602). Mind you this is still not released, but it will work with `comit-rs@master`.
Fixes #52.
---
As a side note, it is extremely painful to test this using `create-comit-app`.
> Make expiries optional

- CHANGELOG.md
- src/comitClient.ts
- src/negotiation/execution_params.spec.ts
- src/negotiation/execution_params.ts
- src/negotiation/maker_negotiator.ts
- src/negotiation/taker_negotiator.ts
Implement this protocol negotiation improvement:
```
// This (finding swap using order details)
// should be simplified by retrieving via order id
// Or by doing an extra round trip:
// Taker -->(ask exec params)--> Maker
// Taker <--(exec params)<-- Maker
// Taker -->(send swap req)--> Taker cnd
// Taker -->(accept order, inc. swap id)--> Maker
// Maker -->(retrieve. check and accept with swap id)--> Maker cnd
// In any case, a matching logic to verify that the taker sent
// the correct parameter needs to happen but this verification
// step may not be done in the ComitClient
```
Also, fix auto-accept.
> Improve negotiation protocol by allowing swap retrieval by id

- CHANGELOG.md
- src/actor.ts
- src/index.ts
- src/siren.ts
Resolves #61 (next step is updating the examples which can only be done once this is merged and released)
Note: I opted for passing in the wallets from the outside so that the developer can overwrite them if wanted. 
How to use (e.g. within the examples):
```javascript
const bitcoinWallet = await BitcoinWallet.newInstance(
"regtest",
process.env.BITCOIN_P2P_URI!,
process.env[`BITCOIN_HD_KEY_${index}`]!
);
const ethereumWallet = new EthereumWallet(
process.env.ETHEREUM_NODE_HTTP_URL!,
process.env[`ETHEREUM_KEY_${index}`]!
);
let taker = startActor(bitcoinWallet, ethereumWallet, process.env[`HTTP_URL_CND_${index}`]!, "taker");
```
> Add `createActor` function

- src/negotiation/order.spec.ts
- src/negotiation/order.ts
- src/siren.ts
Bitcoin has to allow a fraction.
It should not use Ethers BigNumber for the conversion.
> treat conversion of Bitcoin different than Ethereum in from Nominal

- CHANGELOG.md
- src/negotiation/maker_negotiator.ts
- src/negotiation/taker_negotiator.ts
This PR introduces some breaking changes to the negotiation protocol:
* `TakerNegotiator` now takes both `comitClient` and `makerNegotiator` in the constructor instead of being passed in every function
* Removed `negotiateAndInitiateSwap` function to make taking orders more implicit for the taker. This simplifies the logic on the application side.
* Renamed `acceptOrder` to `takeOrder` for the taker
> Refactor negotiation protocol

- CHANGELOG.md
- src/index.ts
- src/negotiation/taker_negotiator.ts
`TakerNegotiator`'s constructor directly accept URL to Maker.
See https://github.com/comit-network/comit-js-sdk/issues/90
> No need to initialise a `MakerClient` anymore

- README.md
- package.json
Minor changes around API doc generation. Specifically:
- Specify additional flags for Typedoc markdown generation
- Fix broken img tag (Please remember to close `<img />` tags, orphaned HTML tags will break some Markdown compilers.)
> Update Typedoc markdown generation command

- .gitignore
- package.json
Adds a missed build artifact directory to `.gitignore`.
Part of https://github.com/comit-network/comit.network/pull/22
> Add Typedoc artifacts to gitignore

- README.md
So the logo is properly displayed in the docs.
Noticed that the logo is not properly displayed in
https://deploy-preview-22--comit-network.netlify.com/docs/comit-sdk/index
which is preview of
https://github.com/comit-network/comit.network/pull/22
> Change logo url to be absolute

- .github/workflows/nodejs.yml
- .gitignore
- CHANGELOG.md
Because otherwise the `dist/` folder is not included in the package.
Adding everyone in review so that nobody get surprised by the CI check.
> Add a check to ensure the dist/ folder is not ignored

- package.json
I had problems with the prettier version `"^1.18.2"` on my Mac, it would always touch the `siren.ts` file event though it should not. 
Updating version fixed this problem.
---
For reference, it would move the bracket on line `85` to line `84`:
```
| "working-copy-of"
);
/**
```
would become:
```
| "working-copy-of");
/**
```
CI does not like that...
> Update prettier version

- .githooks/pre-commit
- package.json
1. The pre-commit hook script no longer worked because the scripts have been changed and merged into a single `test` script without updating the hook.
2. People seem to not use the hook otherwise we would have noticed earlier. The 2nd patch automatically installs the hooks again before running the tests.
At some point, each dev will run `yarn test` and therefore install the hooks again.
The pre-commit hook takes a bit longer now because all the checks have been merged into a single script `test`. I didn't change that because I assume it was on purpose.
If people don't want to run these checks on every commit, I recommend to split the script again.
> Fix pre commit hook

- logo.svg
* Update logo to version without TM (as updated in notion)
* Add a white rectangle and gradient rectangle for good looks
Resolves: https://github.com/comit-network/comit.network/issues/31
> Update logo to support dark mode

- src/index.ts
- src/negotiation/maker/maker_negotiator.ts
- src/negotiation/taker/taker_negotiator.spec.ts
- src/negotiation/taker/taker_negotiator.ts
Files with same name cause problem when rendering the documentation. There are 2 `Negotiator` entries displayed under `Classes` and it is just not visible which is which.
Making the names explicit does not add disadvantages.
> Explicit names for Taker- and MakerNegotiator

- CHANGELOG.md
- src/cnd/axios_rfc7807_middleware.ts
- src/cnd/cnd.spec.ts
- src/cnd/cnd.ts
- src/index.ts
We use axios interceptor functionality to parse responses of type 'application/problem+json' into a Problem class. This allows us to know about the fields present in the response and return a dedicated error to the user with useful information of what went wrong.
Resolves #122.
> Extend Cnd class with middleware for parsing problem responses

- src/cnd/axios_rfc7807_middleware.ts
- src/cnd/cnd.spec.ts
- src/cnd/cnd.ts
- src/swap.spec.ts
- src/swap.ts
- src/wallet/lightning.ts
_99% review_
I have selected the following approach for this PR after considering the feedback provided. I decided not to go with tuples as per @yosriady's [suggestion](https://github.com/comit-network/comit-js-sdk/pull/152#issuecomment-595603819) simply because it is a lot of work as I'd need to catch all failures to transform them to Promise resolution. It is also easy to miss. If we miss it would mean that the user end-up with a thrown error when they do not expect one.
We propagate by throwing when any error is encountered.
We try to _intercept_ any error to add more context to them (see `Problem` and `ChainError` classes)
The idea is that the lib consumer can catch those errors and manipulate them easily, as follow:
```
try {
swap.redeem();
} catch (error) {
if (error instanceOf …
```
> Document cnd errors, wrap cnd & wallet errors in specialised Error classes

- CHANGELOG.md
- src/cnd/cnd.ts
- src/index.ts
- src/transaction.spec.ts
- src/transaction.ts
Few fixes after integration 0.14.1 in comit-rs e2e tests with https://github.com/comit-network/comit-rs/pull/2305.
Redesign of the body request for the lighting routes:
- 7d57d6879a27fed840357244eb1b8e15e110602d: Rename the `*_network` for Ethereum to `chain_id`. This is because for Ethereum it is a `number`. I think using different types (`string` for Bitcoin) with the same name `*_network` is just going to lead to issues.
- f87f48259b2aa98ad231d58e2db736ffc13731d5: Nest Alpha and Beta parameters. After working on this today and yesterday and integrating in the e2e tests (https://github.com/comit-network/comit-rs/pull/2305) I just find the flat structure and repetition of `alpha_` and `beta_` painful. Hence the new proposal.
> Integrations fixes

- CHANGELOG.md
- src/transaction.spec.ts
- src/transaction.ts
Ready for review, usage is in https://github.com/comit-network/comit-rs/pull/2313
A supplementary API could be make `Transaction` an event emitter. At this stage I'd prefer to see the need for it from the PoC before investigating time in it.
> Fix rejection on getting Ethereum transaction status

- CHANGELOG.md
- src/util/timeout_promise.ts
- src/wallet/bitcoin.ts
These are a couple of patches that need to be released before comit-network/comit-rs#2330 can be merged in.
> Add close method for bcoin wallet

- bors.toml
This is to prevent absence-minded developers to trigger bors even
though they set a no-mergify label in purpose to do some clean up
before merging a pull request.
> Stop bors to proceed if the `no-mergify` label is present

- CHANGELOG.md
- package.json
- src/index.ts
- src/wallet/bitcoin.ts
- types/satoshi_bitcoin/index.d.ts
Tentatively fixes #177.
- Only after playing around with a little example inside `create-comit-app` (trying to keep the HD key functionality) did I realise that there is a `bitcoin-core` JS library that we use in `comit-rs` to instantiate a Bitcoin RPC client. I still kind of prefer to use `axios`, since we have to maintain our own types to use that other library anyway, but I may be wrong.
- These changes have been tested against a modified branch of `comit-rs`. See comit-network/comit-rs#2446.
> Replace bcoin wallet with bitcoind wallet

- .github/workflows/draft-new-release.yml
- .github/workflows/release.yml
This will now publish a release upon merging
the PR created by the "draft new release" github action.
It also creates the PR to merge the release
changes it back into the dev branch.
> Add GitHub action to publish release

- .github/workflows/draft-new-release.yml
- .github/workflows/release-pr-ci.yml
GitHub Action does not allow recursion so the
CI checks are not triggers on the release branch
as it is pushed by the "draft new release" action.
So we use repo dispatch to make it happen.
> Trigger checks once release PR is created

- .github/workflows/draft-new-release.yml
- .github/workflows/release-pr-ci.yml
Because the checks are triggered via repo_dispatch
they are not linked to the draft release PR.
Hence, to make it easier to find them, a link is
provided in the body of the PR and the branch
is used in a matrix, allowing it to be present in
the name of the job on GitHub UI.
> Make it easier to find the checks

- CHANGELOG.md
- src/comit_client.ts
Add getAllSwaps function to comit_client so that a dev does not have to fiddle with low-level api of cnd
Resolves #189
> Add getAllSwaps function to comit_client

- src/cnd/action_payload.ts
- src/swap.ts
- src/wallet/ethereum.ts
cnd tells us against which network a particular action should be executed.
This is now enforced by the sdk.
Resolves #4 
Does this count as a breaking change? The functions are public but we only use it internally.
> Assert chain_id on actions against Ethereum

- CHANGELOG.md
- src/wallet/lightning.ts
The promise returned by `LightningWallet.sendPayment`
now resolves when the payment is `in flight`,
previously resolving when `settled`.
The promise resolves to an async function that itself,
returns when the payment is `settled`.
See https://github.com/comit-network/comit-rs/pull/2553 on how to use the API.
Resolves #180
> `sendPayment` returns when payment is `in flight`

- src/cnd/__snapshots__/cnd.spec.ts.snap
- src/cnd/axios_rfc7807_middleware.spec.ts
- src/cnd/axios_rfc7807_middleware.ts
- src/cnd/cnd.spec.ts
While doing https://github.com/comit-network/comit-rs/pull/2554, I realized that the error messages generated by the problems were actually not that great because I was just using the title of the problem.
This patch aims to make the situation better and also adds tests for the messages that are generated.
> Improve error messages generated from problems

- CHANGELOG.md
- package.json
- src/action.spec.ts
- src/action.ts
- src/index.ts
- src/swap.ts
Trying to finish the "Recommended Unique Action" Project by resolving https://github.com/comit-network/comit-rs/issues/2753
First attempt was to simply release the current dev branch and integrate the latest release in the e2e tests but it includes [breaking changes](https://github.com/comit-network/comit-js-sdk/pull/240) I am not familiar with.
Second attempt was to bring https://github.com/comit-network/comit-js-sdk/pull/241 changes in the comit-rs e2e test. Unfortunately, this is not possible because `Swap.fieldValueResolver()` is private and the only method available to execute an action is `Swap.executeSirenAction()` which take the name of the action and will retrieve the full content from cnd again.
This is the third attempt, cherry pick the RUA changes and releasing them.
> Release 0.16.1

- src/wallet/lightning.ts
Sometimes, lnd returns a `OpenStatusUpdate` that does not contain the outpoint of the channel.
Instead of failing, we wait for the next message.
Hopefully we don't wait forever.
Used in https://github.com/comit-network/comit-rs/pull/3020
> Wait for next message from lnd if channel is not ready
