- src/cnd.ts
Otherwise you have to hardcode a peer address when building a COMIT app.
> Add function to get cnd peer addresses

- src/cnd.ts
This method assumes a certain path structure on cnd side that we don't want to expose publicly.
> Remove getSwap method

- .mergify.yml
Looks like the behaviour is different for GitHub actions
> Fix GitHub Action check naming

- CHANGELOG.md
> Squash versions which were yanked from npmjs.com

- .github/workflows/nodejs.yml
- .github/workflows/release.yml
- src/siren.ts
> Fix CI on master

- CHANGELOG.md
- package.json
- src/cnd.ts
- src/comitClient.ts
- src/negotiation/execution_params.spec.ts
- src/negotiation/execution_params.ts
- src/negotiation/maker_negotiator.ts
- src/negotiation/order.spec.ts
- src/negotiation/order.ts
- src/negotiation/taker_negotiator.ts
- src/swap.ts
- src/timeout_promise.ts
- src/tokens/README.md
- src/tokens/definitions.ts
- src/tokens/tokens.ts
Helps with comit-network/create-comit-app#128
Used in comit-network/create-comit-app#208
> Add negotiation protocol and http implementation

- CHANGELOG.md
- src/cnd.ts
- src/negotiation/execution_params.spec.ts
- src/negotiation/execution_params.ts
- src/negotiation/maker_negotiator.ts
- src/negotiation/order.spec.ts
- src/negotiation/order.ts
- src/negotiation/taker_negotiator.ts
- src/swap.ts
- src/timeout_promise.ts
Follow-up of comments on #60 and comit-network/create-comit-app#208
> Negotiation follow up

- CHANGELOG.md
- package.json
> Release 0.7.2

- src/comitClient.spec.ts
- src/comitClient.ts
Improve readability and add some tests.
See https://github.com/comit-network/comit-js-sdk/pull/66/files#r351996893
> #66 Follow-up

- CHANGELOG.md
- package.json
- src/ethereumWallet.ts
- src/index.ts
- src/negotiation/order.spec.ts
- src/negotiation/order.ts
- src/swap.ts
> Support float for Ethers and ERC-20 Tokens

- CHANGELOG.md
- src/bitcoinWallet.ts
- src/index.ts
With this PR I extracted an interface for the `BitcoinWallet` so that a developer can provide her own bitcoin wallet to the actor. 
This is also needed if you want to provide a specifically configured wallet for Testnet.
I also renamed the `BitcoinWallet` to `InMemoryBitcoinWallet` to indicate that this is for in-memory use only.
> InMemoryBitcoinWallet

- src/ethereumWallet.ts
Looks like ethers interface changed but it went
through the net.
> Fix abi import

- CHANGELOG.md
- src/index.ts
- src/negotiation/maker_negotiator.ts
See comit-network/create-comit-app#371
> Hide MakerHttpApi, add getUrl method

- src/swap.ts
Moving the discussion of https://github.com/comit-network/comit-rs/issues/1867 into the PR that actually would make `tryExecuteAction` and `doLedgerAction` public. 
My opinion:
I think the fastest way forward is to expose the functions. When we change the SDK we might have to eventually move this logic into the e2e tests. While I feel it is not right to expose them, I also feel we don't have to be overly careful at the moment because the SDK will change anyway, and once it changes we adapt the e2e tests 🤷‍♂️
> Expose functions to use them for over-/underfunded HTLC tests

- README.md
- logo.svg
How it would look: https://github.com/comit-network/comit-js-sdk/blob/update-readme/README.md
Extended the README significantly to explain the purpose of the SDK and what one can do with it in more detail. 
Note that this README will also serve as the entry point to the SDK-documentation. (Some minor changes might be needed once we actually have the generated documentation.)
> Enhance README and add specific logo

- .github/workflows/nodejs.yml
- .npmignore
Thank you @yosriady for the tip. This is exactly why we were excited to have an experienced JS developer helping us :)
Confirmed working  as expected (`dist/` folder gets published) using dry run:
```
▶ npm publish --dry-run
> comit-sdk@0.11.1 prepare .
> tsc
npm notice 
npm notice 📦  comit-sdk@0.11.1
npm notice === Tarball Contents === 
npm notice 17B    .prettierignore                                         
npm notice 11.4kB LICENSE                                                 
npm notice 76B    .githooks/pre-commit                                    
npm notice 3.3kB  dist/src/action_to_http_request.js                      
npm notice 1.6kB  dist/src/actor.js                                       
npm notice 672B   dist/src/__mocks__/bitcoin_wallet.js                    
npm …
```
> GitIgnore dist/ dir but still publish it

- .prettierignore
- CHANGELOG.md
- src/cnd.ts
- tsconfig.json
Hopefully there is no copy-pasta.
Resolves #117.
> Add route for lightning request on cnd

- src/negotiation/taker/__mocks__/maker_client.ts
- src/negotiation/taker/maker_client.ts
Missed these two fixes when writing the docs, see https://github.com/comit-network/comit.network/pull/22#issuecomment-588528096
> Fix comment errors due to pointy brackets

- CHANGELOG.md
- src/__mocks__/bitcoin_wallet.ts
- src/bitcoin_wallet.ts
- src/cnd/__mocks__/cnd.ts
- src/cnd/cnd.ts
- src/comit_client.ts
- src/ethereum_wallet.ts
- src/negotiation/maker/negotiator.ts
- src/negotiation/taker/order.ts
- src/swap.ts
- src/util/timeout_promise.ts
- tslint.json
> More lints

- README.md
> Make links point to documentation

- .gitignore
- CHANGELOG.md
- package.json
- src/cnd/cnd.ts
- src/comit_client.ts
- src/index.ts
- src/lightning_wallet.ts
- src/lnd.ts
- src/swap.ts
This allows the use of comit-sdk to make current comit-rs e2e lnd tests pass.
See https://github.com/comit-network/comit-rs/pull/2107 for the e2e side.
Resolves #118.
> Add Lightning support for actions

- src/wallet/bitcoin.ts
Resolves https://github.com/comit-network/comit-js-sdk/issues/149
> Better documentation of provided BitcoinWallet

- .github/workflows/trigger-sync-labels.yml
Must be merged to master before I can test it...
> Add sync-labels repository_dispatch

- .github/workflows/trigger-sync-labels.yml
> Sync labels

- src/cnd/cnd.ts
- src/swap.ts
- src/transaction.spec.ts
- src/transaction.ts
- src/wallet/ethereum.ts
> Return new `Transaction` class from Ethereum actions

- .github/workflows/draft-new-release.yml
Helps with #181.
Cross fingers and hope it works, will test once merged.
> Add GitHub action to draft new release

- .github/workflows/release-pr-ci.yml
> Cannot use dynamic variable in matrix

- CHANGELOG.md
- package.json
Reverting this release so I can do it again as the GitHub Action failed when trying to create the GitHub release.
> Revert 0.15.4

- .mergify.yml
Done as part of https://github.com/comit-network/comit-rs/issues/2333
> Remove the changelog bot

- CHANGELOG.md
- declarations/src/action.d.ts
- declarations/src/index.d.ts
- declarations/src/swap.d.ts
- src/action.spec.ts
- src/action.ts
- src/index.ts
- src/swap.ts
Update the SDK to support cnd's recommended unique action as per the project.
See the usage in e2e: https://github.com/comit-network/comit-rs/pull/2765
> Recommended Unique Action

- CHANGELOG.md
- declarations/src/transaction.d.ts
- declarations/src/wallet/__mocks__/bitcoin.d.ts
- declarations/src/wallet/bitcoin.d.ts
- src/swap.ts
- src/transaction.spec.ts
- src/transaction.ts
- src/wallet/__mocks__/bitcoin.ts
- src/wallet/bitcoin.ts
> Add support for Bitcoin to Transaction
